### ISSUE TITLE
missing wormbase/names/responses.clj ?

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#128]
I get this error when starting the ring server on the latest develop.

```
Exception in thread "main" java.io.FileNotFoundException: Could not locate wormbase/names/responses__init.class or wormbase/names/responses.clj on classpath., compiling:(wormbase/names/gene.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:703)
	at wormbase.names.errhandlers$eval34152$loading__6434__auto____34153.invoke(errhandlers.clj:1)
	at wormbase.names.errhandlers$eval34152.invokeStatic(errhandlers.clj:1)
	at wormbase.names.errhandlers$eval34152.invoke(errhandlers.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:3659)
	at wormbase.names.service$eval14502$loading__6434__auto____14503.invoke(service.clj:1)
	at wormbase.names.service$eval14502.invokeStatic(service.clj:1)
	at wormbase.names.service$eval14502.invoke(service.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:3894)
	at user$eval15.invokeStatic(form-init6660167099715742797.clj:1)
	at user$eval15.invoke(form-init6660167099715742797.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate wormbase/names/responses__init.class or wormbase/names/responses.clj on classpath.
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:3659)
	at wormbase.names.gene$eval34712$loading__6434__auto____34713.invoke(gene.clj:1)
	at wormbase.names.gene$eval34712.invokeStatic(gene.clj:1)
	at wormbase.names.gene$eval34712.invoke(gene.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 95 more
Subprocess failed
```

**Comment by sibyl229** [comment]
Hi @mgrbyte I think the original problem is fixed, but I encountered a different issue (copied below). Could you take a look at it sometime?

```
13:44:41.257 ERROR compojure.api.exception [qtp330177744-56]
java.io.FileNotFoundException: Could not locate wormids/core__init.class or wormids/core.clj on classpath.
java.util.concurrent.ExecutionException: java.io.FileNotFoundException: Could not locate wormids/core__init.class or wormids/core.clj on classpath.
```
Thanks!

**Comment by mgrbyte** [comment]
Can't reproduce locally.
Perhaps you can ping me on slack and we can figure it out?

**Comment by sibyl229** [comment]
Another piece of clue. I experience this issue **only** on the branch for the UI side of the species work: https://github.com/WormBase/names/pull/130, which is up to date with `develop` but has changes to some javascript files. I'm curious if you experience similar errors on that branch.

The problem occurs when I try to create a new gene.

Copied below are the errors I get:
```
Started nREPL server on port 54929
Started server on port 4010
15:16:51.271 ERROR compojure.api.exception [qtp215376372-60]
java.io.FileNotFoundException: Could not locate wormids/core__init.class or wormids/core.clj on classpath.
java.util.concurrent.ExecutionException: java.io.FileNotFoundException: Could not locate wormids/core__init.class or wormids/core.clj on classpath.
	at datomic.promise$throw_executionexception_if_throwable.invokeStatic(promise.clj:10)
	at datomic.promise$throw_executionexception_if_throwable.invoke(promise.clj:6)
	at datomic.promise$settable_future$reify__4954.deref(promise.clj:54)
	at clojure.core$deref.invokeStatic(core.clj:2312)
	at clojure.core$deref.invoke(core.clj:2298)
	at wormbase.names.gene$new_gene.invokeStatic(gene.clj:142)
	at wormbase.names.gene$new_gene.doInvoke(gene.clj:140)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at buddy.auth.accessrules$restrict$fn__27786.invoke(accessrules.clj:374)
	at compojure.api.resource$handle_sync.invokeStatic(resource.clj:96)
	at compojure.api.resource$handle_sync.invoke(resource.clj:91)
	at compojure.api.resource$create_handler$fn__26761.invoke(resource.clj:120)
	at compojure.api.routes.Route.invoke(routes.clj:90)
	at compojure.core$routing$fn__4768.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__4772.invoke(core.clj:192)
	at compojure.api.compojure_compat$make_context$handler__24285.invoke(compojure_compat.clj:26)
	at compojure.api.compojure_compat$make_context$fn__24287.invoke(compojure_compat.clj:34)
	at compojure.api.routes.Route.invoke(routes.clj:90)
	at compojure.core$routing$fn__4768.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__4772.invoke(core.clj:192)
	at compojure.api.routes.Route.invoke(routes.clj:90)
	at compojure.core$routing$fn__4768.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__4772.invoke(core.clj:192)
	at compojure.api.compojure_compat$make_context$handler__24285.invoke(compojure_compat.clj:26)
	at compojure.api.compojure_compat$make_context$fn__24287.invoke(compojure_compat.clj:34)
	at compojure.api.routes.Route.invoke(routes.clj:90)
	at compojure.core$routing$fn__4768.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__4772.invoke(core.clj:192)
	at compojure.api.compojure_compat$make_context$handler__24285.invoke(compojure_compat.clj:26)
	at compojure.api.routes.Route.invoke(routes.clj:90)
	at compojure.core$routing$fn__4768.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__4772.invoke(core.clj:192)
	at compojure.api.routes.Route.invoke(routes.clj:90)
	at ring.swagger.middleware$wrap_swagger_data$fn__25752.invoke(middleware.clj:35)
	at wormbase.names.service$wrap_not_found$fn__39862.invoke(service.clj:32)
	at muuntaja.middleware$wrap_format$fn__21328.invoke(middleware.clj:73)
	at buddy.auth.middleware$wrap_authentication$fn__29803.invoke(middleware.clj:59)
	at buddy.auth.middleware$wrap_authorization$fn__29810.invoke(middleware.clj:110)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__20292.invoke(keyword_params.clj:36)
	at ring.middleware.params$wrap_params$fn__5000.invoke(params.clj:67)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__34002.invoke(absolute_redirects.clj:47)
	at ring.middleware.content_type$wrap_content_type$fn__26312.invoke(content_type.clj:34)
	at ring.middleware.default_charset$wrap_default_charset$fn__33974.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__26342.invoke(not_modified.clj:53)
	at wormbase.db$wrap_datomic$fn__27570.invoke(db.clj:80)
	at ring.middleware.resource$wrap_resource$fn__33931.invoke(resource.clj:37)
	at ring.middleware.content_type$wrap_content_type$fn__26312.invoke(content_type.clj:34)
	at ring.middleware.gzip$wrap_gzip$fn__39855.invoke(gzip.clj:94)
	at compojure.api.middleware$wrap_swagger_data$fn__22349.invoke(middleware.clj:190)
	at compojure.api.middleware$wrap_inject_data$fn__22327.invoke(middleware.clj:96)
	at muuntaja.middleware$wrap_params$fn__21324.invoke(middleware.clj:52)
	at compojure.api.middleware$wrap_exceptions$fn__22316.invoke(middleware.clj:62)
	at muuntaja.middleware$wrap_format_request$fn__21336.invoke(middleware.clj:114)
	at compojure.api.middleware$wrap_exceptions$fn__22316.invoke(middleware.clj:62)
	at muuntaja.middleware$wrap_format_response$fn__21340.invoke(middleware.clj:132)
	at muuntaja.middleware$wrap_format_negotiate$fn__21333.invoke(middleware.clj:96)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__20292.invoke(keyword_params.clj:36)
	at ring.middleware.nested_params$wrap_nested_params$fn__20350.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__5000.invoke(params.clj:67)
	at compojure.api.middleware$wrap_inject_data$fn__22327.invoke(middleware.clj:96)
	at compojure.api.routes.Route.invoke(routes.clj:90)
	at clojure.lang.Var.invoke(Var.java:381)
	at ring.middleware.reload$wrap_reload$fn__2752.invoke(reload.clj:39)
	at ring.middleware.stacktrace$wrap_stacktrace_log$fn__1209.invoke(stacktrace.clj:26)
	at ring.middleware.stacktrace$wrap_stacktrace_web$fn__1275.invoke(stacktrace.clj:96)
	at ring.adapter.jetty$proxy_handler$fn__485.invoke(jetty.clj:25)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: Could not locate wormids/core__init.class or wormids/core.clj on classpath.
	at user$eval40787$fn__40788.invoke(form-init4618807177173882364.clj:1)
	at datomic.error$deserialize_exception.invokeStatic(error.clj:135)
	at datomic.error$deserialize_exception.invoke(error.clj:117)
	at datomic.peer.Connection.notify_error(peer.clj:399)
	at datomic.connector$fn__8757.invokeStatic(connector.clj:169)
	at datomic.connector$fn__8757.invoke(connector.clj:167)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at datomic.connector$create_hornet_notifier$fn__8763$fn__8764$fn__8767$fn__8768.invoke(connector.clj:194)
	at datomic.connector$create_hornet_notifier$fn__8763$fn__8764$fn__8767.invoke(connector.clj:189)
	at datomic.connector$create_hornet_notifier$fn__8763$fn__8764.invoke(connector.clj:187)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 common frames omitted
```

**Comment by sibyl229** [comment]
Closing. Thanks to @mgrbyte for figuring this one out. The problem has to do with how the transactor is run.  It either needs to have: 
- `DATOMIC_EXT_CLASSPATH=<path-to-wormids.jar>` OR 
- simply use an in-memory transactor like `datomic:mem://whatever`.

To create the wormid jar:
```
clojure -Sdeps '{:deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git" :sha "8acf80dd4d6e5173585f5c6fec7af28a310f3ed7"}}}' -m mach.pack.alpha.skinny --no-libs --project-path wormids.jar
```
