### ISSUE TITLE
500 error No implementation of method: :write-body-to-stream of protocol

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#183]
How to reproduce (simplified): 
- Go to the create gene page, click on "Create" button without filling in the form.

How to reproduce (original): 
- Create a gene with only the cgc name and species
- Edit the gene that's been created by removing the CGC

Expect: validation error message
Observed: 500 error about "No implementation of method: :write-body-to-stream of protocol:"

```
11:48:14.422 WARN  org.eclipse.jetty.server.HttpChannel [qtp1382027131-58]
/api/gene/WBGene00000001
java.lang.IllegalArgumentException: No implementation of method: :write-body-to-stream of protocol: #'ring.core.protocols/StreamableResponseBody found for class: clojure.lang.PersistentArrayMap
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at ring.core.protocols$eval366$fn__367$G__357__376.invoke(protocols.clj:8)
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:106)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:95)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
	at ring.adapter.jetty$proxy_handler$fn__486.invoke(jetty.clj:26)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mgrbyte** [comment]
Hopefully this is fixed in the latest commit ([develop][1])

[1]: a46e78623939412a45af2290ed722d1153fba387

**Comment by sibyl229** [comment]
Thanks Matt! I will check and let you know.

**Comment by mgrbyte** [comment]
tested  locally and seems good :+1:  will let you close if it is for you.

**Comment by sibyl229** [comment]
Works perfect! Thanks @mgrbyte
