### ISSUE TITLE
500 error update genes with a history of split event

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#184]
Hi @mgrbyte a bit of an odd problem. Updating a gene is otherwise fine, except when it has previously split into other genes.

Steps to reproduce:
- create a gene (WBGene1) with cgc name and species
- split WBGene1, with the biotype of both WBGene1 and the new Gene set to CDS
- modify the biotype of WBGene1 to Transcript and click on "Update"
- Observe the 500 error

```
12:05:22.686 ERROR compojure.api.exception [qtp2032075943-54]
Schema not installed!
clojure.lang.ExceptionInfo: Schema not installed!
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at wormbase.names.errhandlers$handle_missing.invokeStatic(errhandlers.clj:81)
	at wormbase.names.errhandlers$handle_missing.invoke(errhandlers.clj:79)
	at wormbase.names.errhandlers$handle_txfn_error.invokeStatic(errhandlers.clj:115)
	at wormbase.names.errhandlers$handle_txfn_error.invoke(errhandlers.clj:105)
	at compojure.api.middleware$call_error_handler.invokeStatic(middleware.clj:41)
	at compojure.api.middleware$call_error_handler.invoke(middleware.clj:30)
	at compojure.api.middleware$wrap_exceptions$rethrow_or_respond__22470.invoke(middleware.clj:57)
	at compojure.api.middleware$wrap_exceptions$fn__22472.invoke(middleware.clj:64)
	at muuntaja.middleware$wrap_format_request$fn__21492.invoke(middleware.clj:114)
	at compojure.api.middleware$wrap_exceptions$fn__22472.invoke(middleware.clj:62)
	at muuntaja.middleware$wrap_format_response$fn__21496.invoke(middleware.clj:132)
	at muuntaja.middleware$wrap_format_negotiate$fn__21489.invoke(middleware.clj:96)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__20441.invoke(keyword_params.clj:53)
	at ring.middleware.nested_params$wrap_nested_params$fn__20499.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__5001.invoke(params.clj:67)
	at compojure.api.middleware$wrap_inject_data$fn__22483.invoke(middleware.clj:96)
	at compojure.api.routes.Route.invoke(routes.clj:90)
	at clojure.lang.Var.invoke(Var.java:381)
	at ring.middleware.reload$wrap_reload$fn__2753.invoke(reload.clj:39)
	at ring.middleware.stacktrace$wrap_stacktrace_log$fn__1210.invoke(stacktrace.clj:26)
	at ring.middleware.stacktrace$wrap_stacktrace_web$fn__1276.invoke(stacktrace.clj:96)
	at ring.adapter.jetty$proxy_handler$fn__486.invoke(jetty.clj:25)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mgrbyte** [comment]
Hi @sibyl229 , think I've found the problem.

Adding `(prn data)` above the following line in the code reveals the issue (it should be printed out with the exception, but is not being :thinking: )
https://github.com/WormBase/names/blob/develop/src/wormbase/names/errhandlers.clj#L81

Not sure what the correct way forward is yet, but here's what's occurring:
 - The info stored in the data being submitted to the last update step :up:  contains data/keys that it shouldn't/are not valid.
 - The things that are not valid to send to an update/delete/create endpoint for Gene are:
   - `split-into`, `split-from`, `merged-into`, `merged-from` [1] ; these are present in the body of the "read gene" endpoint's  (GET /gene/`<id>`) (these are "virtual" fields that show what a gene is currently split/merged into/from)
  - these are being resubmitted.

Options:
 1. server should strip the keys it doesn't want from the payload
 2. client shouldn't send what the server isn't expecting.

Should the server complain if it gets a key in the data it doesn't want or ignore? :thinking: 
Probably it's 1 and 2, but only 1 is "mandatory", will go away and think about this, take any input people have then cook up a patch.

**Comment by sibyl229** [comment]
Thanks @mgrbyte ! I initially thought that was the problem too. I have already taken care of option 2. But the problem still happens.

![Screen Shot 2019-03-26 at 1 39 15 PM](https://user-images.githubusercontent.com/1753893/55020203-c0ea1600-4fcc-11e9-8a9c-65e3393811f2.png)

Edit: the branch `refactor-page` has the fix for option 2

**Comment by mgrbyte** [comment]
@sibyl229 I tried checking out and testing with your `refactor-page` branch, but get:
```
yarn build
yarn run v1.12.3
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '../../utils/format' in '/home/matt/git/wormbase-names/client/src/components/elements'


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sibyl229** [comment]
@mgrbyte good call! I forgot to check in a file. refactor-page branch should be fixed for the "can't resolve" bug.

**Comment by sibyl229** [comment]
Thanks @mgrbyte ! Split event no longer causes problem now
