### ISSUE TITLE
error loading wormbase/ids/core__init.class with-profile prod

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#228]
I started the server with: `WB_DB_URI=datomic:ddb://us-east-1/WSNames/05032019 lein with-profile prod ring server-headless 9010` (note the with-profile). The following problem when creating a gene.

```
18:15:33.361 ERROR compojure.api.exception [qtp716964294-51]
java.io.FileNotFoundException: Could not locate wormbase/ids/core__init.class or wormbase/ids/core.clj on classpath.
java.util.concurrent.ExecutionException: java.io.FileNotFoundException: Could not locate wormbase/ids/core__init.class or wormbase/ids/core.clj on classpath.
        at datomic.promise$throw_executionexception_if_throwable.invokeStatic(promise.clj:10)
        at datomic.promise$throw_executionexception_if_throwable.invoke(promise.clj:6)
        at datomic.promise$settable_future$reify__4954.deref(promise.clj:54)
        at clojure.core$deref.invokeStatic(core.clj:2312)
        at clojure.core$deref.invoke(core.clj:2298)
        at wormbase.names.entity$creator$handle_new__32889.invoke(entity.clj:40)
        at wormbase.names.gene$handle_new__33043.invokeStatic(gene.clj:372)
        at wormbase.names.gene$handle_new__33043.invoke(gene.clj:366)
        at compojure.api.resource$handle_sync.invokeStatic(resource.clj:95)
        at compojure.api.resource$handle_sync.invoke(resource.clj:90)
        at compojure.api.resource$create_handler$fn__17169.invoke(resource.clj:119)
        at compojure.api.routes.Route.invoke(routes.clj:89)
        at compojure.core$routing$fn__3844.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__3848.invoke(core.clj:192)
        at compojure.api.compojure_compat$make_context$handler__14699.invoke(compojure_compat.clj:26)
        at compojure.api.compojure_compat$make_context$fn__14701.invoke(compojure_compat.clj:34)
        at compojure.api.routes.Route.invoke(routes.clj:89)
        at compojure.core$routing$fn__3844.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__3848.invoke(core.clj:192)
        at compojure.api.routes.Route.invoke(routes.clj:89)
        at compojure.core$routing$fn__3844.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__3848.invoke(core.clj:192)
        at buddy.auth.accessrules$restrict$fn__22335.invoke(accessrules.clj:374)
        at compojure.api.compojure_compat$make_context$handler__14699.invoke(compojure_compat.clj:26)
        at compojure.api.compojure_compat$make_context$fn__14701.invoke(compojure_compat.clj:34)
        at compojure.api.routes.Route.invoke(routes.clj:89)
        at compojure.core$routing$fn__3844.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__3848.invoke(core.clj:192)
        at compojure.api.compojure_compat$make_context$handler__14699.invoke(compojure_compat.clj:26)
        at compojure.api.routes.Route.invoke(routes.clj:89)
        at compojure.core$routing$fn__3844.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__3848.invoke(core.clj:192)
        at compojure.api.routes.Route.invoke(routes.clj:89)
        at ring.swagger.middleware$wrap_swagger_data$fn__16154.invoke(middleware.clj:35)
        at wormbase.names.service$wrap_not_found$fn__33635.invoke(service.clj:35)
        at muuntaja.middleware$wrap_format$fn__11733.invoke(middleware.clj:73)
        at buddy.auth.middleware$wrap_authentication$fn__24352.invoke(middleware.clj:59)
        at buddy.auth.middleware$wrap_authorization$fn__24359.invoke(middleware.clj:110)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__10520.invoke(keyword_params.clj:53)
        at ring.middleware.params$wrap_params$fn__4076.invoke(params.clj:67)
        at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__28632.invoke(absolute_redirects.clj:47)
        at ring.middleware.content_type$wrap_content_type$fn__16714.invoke(content_type.clj:34)
        at ring.middleware.default_charset$wrap_default_charset$fn__28604.invoke(default_charset.clj:31)
        at ring.middleware.not_modified$wrap_not_modified$fn__16747.invoke(not_modified.clj:61)
        at wormbase.db$wrap_datomic$fn__22119.invoke(db.clj:80)
        at ring.middleware.resource$wrap_resource_prefer_resources$fn__28549.invoke(resource.clj:25)
        at ring.middleware.content_type$wrap_content_type$fn__16714.invoke(content_type.clj:34)
        at ring.middleware.gzip$wrap_gzip$fn__33628.invoke(gzip.clj:94)
        at compojure.api.middleware$wrap_swagger_data$fn__12754.invoke(middleware.clj:190)
        at compojure.api.middleware$wrap_inject_data$fn__12732.invoke(middleware.clj:96)
        at muuntaja.middleware$wrap_params$fn__11729.invoke(middleware.clj:52)
        at compojure.api.middleware$wrap_exceptions$fn__12721.invoke(middleware.clj:62)
        at muuntaja.middleware$wrap_format_request$fn__11741.invoke(middleware.clj:114)
        at compojure.api.middleware$wrap_exceptions$fn__12721.invoke(middleware.clj:62)
        at muuntaja.middleware$wrap_format_response$fn__11745.invoke(middleware.clj:132)
        at muuntaja.middleware$wrap_format_negotiate$fn__11738.invoke(middleware.clj:96)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__10520.invoke(keyword_params.clj:53)
        at ring.middleware.nested_params$wrap_nested_params$fn__10578.invoke(nested_params.clj:89)
        at ring.middleware.params$wrap_params$fn__4076.invoke(params.clj:67)
        at compojure.api.middleware$wrap_inject_data$fn__12732.invoke(middleware.clj:96)
        at compojure.api.routes.Route.invoke(routes.clj:89)
        at clojure.lang.Var.invoke(Var.java:381)
        at ring.middleware.reload$wrap_reload$fn__1828.invoke(reload.clj:39)
        at ring.middleware.stacktrace$wrap_stacktrace_log$fn__1210.invoke(stacktrace.clj:26)
        at ring.middleware.stacktrace$wrap_stacktrace_web$fn__1276.invoke(stacktrace.clj:96)
        at ring.adapter.jetty$proxy_handler$fn__486.invoke(jetty.clj:25)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: Could not locate wormbase/ids/core__init.class or wormbase/ids/core.clj on classpath.
        at user$eval33776$fn__33777.invoke(form-init7074573165466394781.clj:1)
        at datomic.error$deserialize_exception.invokeStatic(error.clj:135)
        at datomic.error$deserialize_exception.invoke(error.clj:117)
        at datomic.peer.Connection.notify_error(peer.clj:399)
        at datomic.connector$fn__8757.invokeStatic(connector.clj:169)
        at datomic.connector$fn__8757.invoke(connector.clj:167)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at datomic.connector$create_hornet_notifier$fn__8763$fn__8764$fn__8767$fn__8768.invoke(connector.clj:194)
        at datomic.connector$create_hornet_notifier$fn__8763$fn__8764$fn__8767.invoke(connector.clj:189)
        at datomic.connector$create_hornet_notifier$fn__8763$fn__8764.invoke(connector.clj:187)
        at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 common frames omitted

```

**Comment by mgrbyte** [comment]
Now working in production, I've put more details in slack pm @sibyl229
