### ISSUE TITLE
/api/entity 500 error

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#258]
The part in the stack trace that stands out is `Schema :person/email not installed!` I don't know how to install it. I'm using an in-memory database.
```
12:22:25.269 ERROR compojure.api.exception [qtp421101181-27]

java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:35)
	at com.google.api.client.json.webtoken.JsonWebSignature$Parser.parse(JsonWebSignature.java:529)
	at com.google.api.client.googleapis.auth.oauth2.GoogleIdToken.parse(GoogleIdToken.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:332)
	at wormbase.names.auth$parse_token.invokeStatic(auth.clj:41)
	at wormbase.names.auth$parse_token.invoke(auth.clj:40)
	at wormbase.names.auth$identify.invokeStatic(auth.clj:95)
	at wormbase.names.auth$identify.invoke(auth.clj:93)
	at buddy.auth.backends.token$token_backend$reify__33836._authenticate(token.clj:89)
	at buddy.auth.middleware$authenticate_request.invokeStatic(middleware.clj:39)
	at buddy.auth.middleware$authenticate_request.invoke(middleware.clj:25)
	at buddy.auth.middleware$authentication_request.invokeStatic(middleware.clj:49)
	at buddy.auth.middleware$authentication_request.doInvoke(middleware.clj:42)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at buddy.auth.middleware$wrap_authentication$fn__33864.invoke(middleware.clj:60)
	at buddy.auth.middleware$wrap_authorization$fn__33871.invoke(middleware.clj:114)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__17688.invoke(keyword_params.clj:53)
	at ring.middleware.params$wrap_params$fn__4163.invoke(params.clj:67)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__37626.invoke(absolute_redirects.clj:47)
	at ring.middleware.content_type$wrap_content_type$fn__23741.invoke(content_type.clj:34)
	at ring.middleware.default_charset$wrap_default_charset$fn__37598.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__23774.invoke(not_modified.clj:61)
	at wormbase.db$wrap_datomic$fn__29561.invoke(db.clj:77)
	at ring.middleware.resource$wrap_resource_prefer_resources$fn__37543.invoke(resource.clj:25)
	at ring.middleware.content_type$wrap_content_type$fn__23741.invoke(content_type.clj:34)
	at ring.middleware.gzip$wrap_gzip$fn__40507.invoke(gzip.clj:100)
	at compojure.api.middleware$wrap_swagger_data$fn__19779.invoke(middleware.clj:190)
	at compojure.api.middleware$wrap_inject_data$fn__19757.invoke(middleware.clj:96)
	at muuntaja.middleware$wrap_params$fn__18754.invoke(middleware.clj:52)
	at compojure.api.middleware$wrap_exceptions$fn__19746.invoke(middleware.clj:62)
	at muuntaja.middleware$wrap_format_request$fn__18766.invoke(middleware.clj:114)
	at compojure.api.middleware$wrap_exceptions$fn__19746.invoke(middleware.clj:62)
	at muuntaja.middleware$wrap_format_response$fn__18770.invoke(middleware.clj:132)
	at muuntaja.middleware$wrap_format_negotiate$fn__18763.invoke(middleware.clj:96)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__17688.invoke(keyword_params.clj:53)
	at ring.middleware.nested_params$wrap_nested_params$fn__17746.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__4163.invoke(params.clj:67)
	at compojure.api.middleware$wrap_inject_data$fn__19757.invoke(middleware.clj:96)
	at compojure.api.routes.Route.invoke(routes.clj:89)
	at clojure.lang.Var.invoke(Var.java:384)
	at ring.middleware.reload$wrap_reload$fn__1914.invoke(reload.clj:39)
	at ring.middleware.stacktrace$wrap_stacktrace_log$fn__1201.invoke(stacktrace.clj:26)
	at ring.middleware.stacktrace$wrap_stacktrace_web$fn__1267.invoke(stacktrace.clj:96)
	at ring.adapter.jetty$proxy_handler$fn__477.invoke(jetty.clj:26)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:745)
12:22:25.990 ERROR compojure.api.exception [qtp421101181-26]
Schema :person/email not installed!
clojure.lang.ExceptionInfo: Schema :person/email not installed!
	at wormbase.names.errhandlers$handle_missing.invokeStatic(errhandlers.clj:87)
	at wormbase.names.errhandlers$handle_missing.invoke(errhandlers.clj:85)
	at wormbase.names.errhandlers$handle_unexpected_error.invokeStatic(errhandlers.clj:106)
	at wormbase.names.errhandlers$handle_unexpected_error.invoke(errhandlers.clj:102)
	at wormbase.names.errhandlers$handle_txfn_error.invokeStatic(errhandlers.clj:136)
	at wormbase.names.errhandlers$handle_txfn_error.invoke(errhandlers.clj:113)
	at compojure.api.middleware$call_error_handler.invokeStatic(middleware.clj:41)
	at compojure.api.middleware$call_error_handler.invoke(middleware.clj:30)
	at compojure.api.middleware$wrap_exceptions$rethrow_or_respond__19744.invoke(middleware.clj:57)
	at compojure.api.middleware$wrap_exceptions$fn__19746.invoke(middleware.clj:64)
	at muuntaja.middleware$wrap_format_request$fn__18766.invoke(middleware.clj:114)
	at compojure.api.middleware$wrap_exceptions$fn__19746.invoke(middleware.clj:62)
	at muuntaja.middleware$wrap_format_response$fn__18770.invoke(middleware.clj:132)
	at muuntaja.middleware$wrap_format_negotiate$fn__18763.invoke(middleware.clj:96)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__17688.invoke(keyword_params.clj:53)
	at ring.middleware.nested_params$wrap_nested_params$fn__17746.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__4163.invoke(params.clj:67)
	at compojure.api.middleware$wrap_inject_data$fn__19757.invoke(middleware.clj:96)
	at compojure.api.routes.Route.invoke(routes.clj:89)
	at clojure.lang.Var.invoke(Var.java:384)
	at ring.middleware.reload$wrap_reload$fn__1914.invoke(reload.clj:39)
	at ring.middleware.stacktrace$wrap_stacktrace_log$fn__1201.invoke(stacktrace.clj:26)
	at ring.middleware.stacktrace$wrap_stacktrace_web$fn__1267.invoke(stacktrace.clj:96)
	at ring.adapter.jetty$proxy_handler$fn__477.invoke(jetty.clj:26)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by sibyl229** [comment]
@mgrbyte My fault! Sorry about that. I pointed at http://names.wormbase.org. It should have been http**s**.
